---
title: "Olympics Visualisation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load Libraries and dataset
library(tidyverse)
library(plotly)
library(ggplot2)
library(tidytuesdayR)

tuesdata <- tt_load(2024, week = 32)
oly <- tuesdata$olympics
theme_set(theme_minimal())
```



```{r}
df <- oly %>% 
  select(id, name, noc, year, season, city) %>% 
  group_by(id, name) %>% 
  unique() 
```


### Function to visualise participation in the Olympics
```{r}
vis <- function(data, seas = c("Summer", "Winter")){
  top_noc <- data %>% 
    filter(season == seas) %>% 
    group_by(noc) %>% 
    summarise(total_count = n()) %>% 
    ungroup() %>% 
    top_n(5) %>% 
    pull(noc)
  
  df <- data %>% 
    filter(noc %in% top_noc) %>% 
    group_by(year, noc) %>% 
    summarise(count = n(), .groups = 'drop') %>% 
    ungroup() %>% 
    group_by(noc) %>% 
    #mutate(label = ifelse(row_number() == n(), paste0(noc, " - ", count), NA)) %>% 
    ungroup() %>% 
    arrange(year, noc)
  
    # plot <- ggplot(df, aes(x = year, y = count, fill = noc) )+
    #   geom_area()+
    # #geom_line(alpha = 0.6, linewidth = 1) +
    # #geom_text(nudge_x = 3, size = 4)+
    #   labs(title = paste0("Top 5 Country Participation - ", seas, " Olympics"))+
    #   ylab("Total athletes")+
    #   theme_bw()+
    #   theme(legend.position = 'bottom',
    #       legend.title = element_blank())
    
    fig <- plot_ly(data = df, 
                   x =~year, 
                   y = ~count, 
                   type = 'scatter', 
                   color = ~noc, 
                   mode = 'line', 
                   stackgroup = 'one',
                   hoverinfo = 'text',
                   hovertext = paste0("Country: ", df$noc,
                                  "<br>Count: ", df$count,
                                  "<br>Year:", df$year) ) %>% 
  layout(title = paste0("Top 5 country participation - ", seas, " Olympics"),
         yaxis = list(title = "Total Athletes"),
         xaxis = list(title = "Year"),
         legend = list(title = list(text = '<b>Country</b>')))
  
    return(fig)
  
}
```


## Winter Olympics visual
```{r}
vis(oly, 'Winter')

# top_noc <- oly %>% filter(season == 'Winter') %>% 
#   group_by(noc) %>% 
#   summarise(total_count = n()) %>% 
#   ungroup() %>% 
#   top_n(5) %>% pull(noc)
# 
# oly %>%
#   filter(noc %in% top_noc) %>% 
#     group_by(year, noc) %>% 
#     summarise(count = n(), .groups = 'drop') %>% 
#     ungroup() %>% 
#     group_by(noc) %>% 
#     mutate(label = ifelse(row_number() == n(), paste0(noc, " - ", count), NA)) %>% 
#     ungroup() %>% 
#     arrange(year, noc) %>% 
#     ggplot(aes(x = year, y = count, fill = noc))+geom_area()+
#     #geom_line(alpha = 0.6, linewidth = 1) +
#     #geom_text(nudge_x = 3, size = 4)+
#     labs(title = paste0("Top 5 Country Participation - Olympics"))+
#     ylab("Number of athletes")+
#     theme_bw()+
#     theme(legend.position = 'bottom',
#           legend.title = element_blank())
```



## Summer Olympics visual
```{r}
vis(oly, 'Summer')
```
## Box plot of Athlete's height by sport

Use the function to visualise height or weight difference over the years in the Olympics.

```{r}

boxplot <- function(sports, gen, metric = c('height', 'weight')){
  
  df <- oly %>% 
    mutate(sex = ifelse(sex == 'M', "Male", "Female"))
  
  if(metric == 'height'){
  fig <- df %>% 
    filter(
      sport == sports,
      sex == gen
    ) %>% 
    ggplot(aes(x = year, y = height))+
    geom_boxplot(aes(group = factor(year)))+
    geom_smooth(method = 'loess', formula = 'y~x', se = FALSE)+
    scale_x_continuous(breaks = 193:201 *10) +
    labs(x = NULL, y = 'Height (cm)',
         title = paste0('Heights of ', gen, ' ', sports, ' athletes in the Olympics'),
         caption = 'Source: Kaggle Olympics history data')+
    theme_bw()
  
  }else{
    fig <- df %>% 
    filter(
      sport == sports,
      sex == gen
    ) %>% 
    ggplot(aes(x = year, y = weight))+
    geom_boxplot(aes(group = factor(year)))+
    geom_smooth(method = 'loess', formula = 'y~x', se = FALSE)+
    scale_x_continuous(breaks = 193:201 *10) +
    labs(x = NULL, y = 'Weight (kg)',
         title = paste0('Weights of ', gen, ' ', sports, ' athletes in the Olympics'),
         caption = 'Source: Kaggle Olympics history data')+
      theme_bw()
  }
  return (fig)  
}

```

```{r}
boxplot("Basketball", "Male", 'height')
```

```{r}
boxplot("Gymnastics", "Female", 'weight')
```



